#include "matrices.h"

const uint MAIN_MATRIX_EXTRA_LEDS[MAIN_MATRIX_EXTRA_LEDS_COUNT] = {10, 21, 32, 43, 54, 75, 86, 97, 108, 119, 130, 141, 152, 173, 194};
uint MAIN_MATRIX_BUF[MAIN_MATRIX_W * MAIN_MATRIX_H];
matrix_with_extra main_matrix = {MAIN_MATRIX_W, MAIN_MATRIX_H, MAIN_OFFSET, MAIN_MATRIX_BUF};

const uint NEXT_PIECE_MATRIX_EXTRA_LEDS[NEXT_PIECE_MATRIX_EXTRA_LEDS_COUNT] = {4, 9, 14, 19};
uint NEXT_PIECE_MATRIX_BUF[NEXT_PIECE_MATRIX_W * NEXT_PIECE_MATRIX_H];
matrix_with_extra next_piece_matrix = {NEXT_PIECE_MATRIX_W, NEXT_PIECE_MATRIX_H, NEXT_PIECE_OFFSET, NEXT_PIECE_MATRIX_BUF};

const uint HOLD_PIECE_MATRIX_EXTRA_LEDS[HOLD_PIECE_MATRIX_EXTRA_LEDS_COUNT] = {4, 9, 14};
uint HOLD_PIECE_MATRIX_BUF[HOLD_PIECE_MATRIX_W * HOLD_PIECE_MATRIX_H];
matrix_with_extra hold_piece_matrix = {HOLD_PIECE_MATRIX_W, HOLD_PIECE_MATRIX_H, HOLD_PIECE_OFFSET, HOLD_PIECE_MATRIX_BUF};

void init_all_matrices()
{
    init_matrix_with_extra(&hold_piece_matrix, HOLD_PIECE_MATRIX_EXTRA_LEDS, HOLD_PIECE_MATRIX_EXTRA_LEDS_COUNT);
    init_matrix_with_extra(&main_matrix, MAIN_MATRIX_EXTRA_LEDS, MAIN_MATRIX_EXTRA_LEDS_COUNT);
    init_matrix_with_extra(&next_piece_matrix, NEXT_PIECE_MATRIX_EXTRA_LEDS, NEXT_PIECE_MATRIX_EXTRA_LEDS_COUNT);
}