#pragma once

#include "pico/stdlib.h"
#include "matrix_with_extra.h"

#define MAIN_MATRIX_W 10
#define MAIN_MATRIX_H 24
#define MAIN_MATRIX_EXTRA_LEDS_COUNT 15
#define MAIN_OFFSET 0

extern const uint MAIN_MATRIX_EXTRA_LEDS[MAIN_MATRIX_EXTRA_LEDS_COUNT];
extern uint MAIN_MATRIX_BUF[MAIN_MATRIX_W * MAIN_MATRIX_H];
extern matrix_with_extra main_matrix;

#define NEXT_PIECE_MATRIX_W 4
#define NEXT_PIECE_MATRIX_H 4
#define NEXT_PIECE_MATRIX_EXTRA_LEDS_COUNT 4
#define NEXT_PIECE_OFFSET (MAIN_OFFSET + (MAIN_MATRIX_W * MAIN_MATRIX_H) + MAIN_MATRIX_EXTRA_LEDS_COUNT)

extern const uint NEXT_PIECE_MATRIX_EXTRA_LEDS[NEXT_PIECE_MATRIX_EXTRA_LEDS_COUNT];
extern uint NEXT_PIECE_MATRIX_BUF[NEXT_PIECE_MATRIX_W * NEXT_PIECE_MATRIX_H];
extern matrix_with_extra next_piece_matrix;

#define HOLD_PIECE_MATRIX_W 4
#define HOLD_PIECE_MATRIX_H 4
#define HOLD_PIECE_MATRIX_EXTRA_LEDS_COUNT 3
#define HOLD_PIECE_OFFSET (NEXT_PIECE_OFFSET + (NEXT_PIECE_MATRIX_W * NEXT_PIECE_MATRIX_H) + NEXT_PIECE_MATRIX_EXTRA_LEDS_COUNT)

extern const uint HOLD_PIECE_MATRIX_EXTRA_LEDS[HOLD_PIECE_MATRIX_EXTRA_LEDS_COUNT];
extern uint HOLD_PIECE_MATRIX_BUF[HOLD_PIECE_MATRIX_W * HOLD_PIECE_MATRIX_H];
extern matrix_with_extra hold_piece_matrix;

#define TOTAL_LED_COUNT (HOLD_PIECE_OFFSET + (HOLD_PIECE_MATRIX_W * HOLD_PIECE_MATRIX_H) + HOLD_PIECE_MATRIX_EXTRA_LEDS_COUNT)

void init_all_matrices();
